version: '3'
services:
  db:
    image: postgres:15-bullseye
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/usr/src/sql

  api:
    build: ./api
    volumes:
      - .:/api:/usr/src/api
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
