version: '3'

services:
  db:
    image: postgres:15-bullseye
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/usr/src/sql

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./api:/app/api

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
        - smtp4dev-data:/smtp4dev
    environment:
      # Uncomment to customise these settings
      - ServerOptions__HostName=smtp4dev

      #The login for the SMTP server used to relay messages
      - RelayOptions__Login=$MAIL_USER

      #The password for the SMTP server used to relay messages
      - RelayOptions__Password=$MAIL_PASSWORD

volumes:
  db:
  smtp4dev-data:
