version: '3'

services:
  db:
    image: postgres:15-bullseye
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/usr/src/sql

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./api:/app/api

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev
      - RelayOptions__Login=$MAIL_USER
      - RelayOptions__Password=$MAIL_PASSWORD
  
  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - "7000:7000"
    env_file:
      - .env
    volumes:
      - ./front:/app/front

    

volumes:
  db:
  smtp4dev-data:
