version: '3'

services:
  db:
    image: postgres:15-bullseye
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/usr/src/sql

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db:
